/**:
  ros__parameters:
    angular_velocity_stddev_xx: 0.0
    angular_velocity_stddev_yy: 0.0
    angular_velocity_stddev_zz: 0.0
    angular_velocity_offset_x: 0.0
    angular_velocity_offset_y: 0.0
    angular_velocity_offset_z: 0.0
