/**:
  ros__parameters:
    camera_frame_id: "camera7/camera_optical_link"
    video_device: "/dev/tlr-right"
    output_encoding: "rgb8"
    image_size: [2880, 1860]
    .image_raw.jpeg_quality: 75
    publish_rate: 10
